name: Daily Zara Product Scraping

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

env:
  PYTHON_VERSION: '3.9'

jobs:
  scrape-zara-products:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_scraper.txt
    
    - name: Run Zara scraper
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        python run_scraper.py --cleanup-days 30
    
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()  # Upload logs even if scraping fails
      with:
        name: scraper-logs
        path: zara_scraper_*.log
        retention-days: 7
    
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Daily Zara scraping failed',
            body: `The daily Zara product scraping job failed on ${new Date().toISOString()}.
            
            Please check the workflow logs for details.
            
            Workflow run: ${context.payload.workflow_run?.html_url || context.payload.repository.html_url + '/actions'}`
          })