name: Daily Zara Scraper

on:
  # Run daily at 9:00 AM UTC
  schedule:
    - cron: '0 9 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main for testing
  push:
    branches: [ main ]
    paths:
      - 'zara_scraper.py'
      - '.github/workflows/zara_scraper.yml'

jobs:
  scrape-zara-products:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright supabase python-dotenv
    
    - name: Install Playwright browsers
      run: |
        playwright install chromium
    
    - name: Run Zara scraper
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python zara_scraper.py
    
    - name: Upload logs as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: scraper-logs-${{ github.run_number }}
        path: |
          *.log
        retention-days: 30